# Generated by Django 5.2 on 2025-04-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('people_involved', models.CharField(max_length=255)),
            ],
        ),
    ]
