# Generated by Django 5.2 on 2025-05-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_todolist_assigned_to_todolist_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='people_involved',
        ),
    ]
